/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasisarpras;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SMK 4
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Connection koneksi;
    public Admin()  {
        initComponents();
        koneksi = KoneksiDatabase.getKoneksi();
        showDashboard();
        LaporanAdmin();
        laporanAdmin1();
        showDataPeminjaman();
        showDataInventaris();
         //agar ditengah page nya
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2 ;
        int y = layar.height / 2 - this.getSize().height / 2 ;
        
        this.setVisible(true);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_panel9 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jpdashboard9 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jpinventaris = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jppeminjaman = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jplaporan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        jpdashboardcontent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        d_pinjam = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        label_ak = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        label_atk = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jppeminjamancontent = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        btn_tambah_peminjaman = new javax.swing.JButton();
        btn_edit_peminjaman = new javax.swing.JButton();
        btn_hapus_peminjaman = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_peminjaman = new javax.swing.JTable();
        btnref = new javax.swing.JButton();
        jplaporancontent = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnsubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpinventariscontent = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        btn_tambah_inventaris1 = new javax.swing.JButton();
        btn_edit_inventaris = new javax.swing.JButton();
        btn_hapus_inventaris = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_inventaris1 = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        last = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        cd = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_peminjaman1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_inventaris = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sarana dan Prasarana SMK 4 | Admin");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        side_panel9.setBackground(new java.awt.Color(38, 42, 51));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/smk4(1).png"))); // NOI18N

        jLabel54.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Versi 1.0");

        jLabel55.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Administrator");

        jpdashboard9.setBackground(new java.awt.Color(38, 42, 51));
        jpdashboard9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpdashboard9MouseClicked(evt);
            }
        });

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Home_20px.png"))); // NOI18N

        jLabel57.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Dashboard");

        javax.swing.GroupLayout jpdashboard9Layout = new javax.swing.GroupLayout(jpdashboard9);
        jpdashboard9.setLayout(jpdashboard9Layout);
        jpdashboard9Layout.setHorizontalGroup(
            jpdashboard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdashboard9Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel57)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpdashboard9Layout.setVerticalGroup(
            jpdashboard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdashboard9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpdashboard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addContainerGap())
        );

        jpinventaris.setBackground(new java.awt.Color(38, 42, 51));
        jpinventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpinventarisMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Broom_20px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inventaris");

        javax.swing.GroupLayout jpinventarisLayout = new javax.swing.GroupLayout(jpinventaris);
        jpinventaris.setLayout(jpinventarisLayout);
        jpinventarisLayout.setHorizontalGroup(
            jpinventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinventarisLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpinventarisLayout.setVerticalGroup(
            jpinventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinventarisLayout.createSequentialGroup()
                .addGroup(jpinventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jppeminjaman.setBackground(new java.awt.Color(38, 42, 51));
        jppeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jppeminjamanMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Suitcase_20px_1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Peminjaman");

        javax.swing.GroupLayout jppeminjamanLayout = new javax.swing.GroupLayout(jppeminjaman);
        jppeminjaman.setLayout(jppeminjamanLayout);
        jppeminjamanLayout.setHorizontalGroup(
            jppeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppeminjamanLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jppeminjamanLayout.setVerticalGroup(
            jppeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppeminjamanLayout.createSequentialGroup()
                .addGroup(jppeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplaporan.setBackground(new java.awt.Color(38, 42, 51));
        jplaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplaporanMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Presentation_20px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Laporan");

        javax.swing.GroupLayout jplaporanLayout = new javax.swing.GroupLayout(jplaporan);
        jplaporan.setLayout(jplaporanLayout);
        jplaporanLayout.setHorizontalGroup(
            jplaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplaporanLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplaporanLayout.setVerticalGroup(
            jplaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplaporanLayout.createSequentialGroup()
                .addGroup(jplaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout side_panel9Layout = new javax.swing.GroupLayout(side_panel9);
        side_panel9.setLayout(side_panel9Layout);
        side_panel9Layout.setHorizontalGroup(
            side_panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpdashboard9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpinventaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(side_panel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(side_panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_panel9Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_panel9Layout.createSequentialGroup()
                        .addGroup(side_panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel53))
                        .addGap(71, 71, 71))))
            .addComponent(jppeminjaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jplaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        side_panel9Layout.setVerticalGroup(
            side_panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panel9Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addGap(36, 36, 36)
                .addComponent(jpdashboard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpinventaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jppeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jplaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content_panel.setBackground(new java.awt.Color(255, 255, 255));
        content_panel.setLayout(new java.awt.CardLayout());

        jpdashboardcontent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 85, 174));

        jLabel59.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addContainerGap())
        );

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 85, 174), 2));

        d_pinjam.setFont(new java.awt.Font("Verdana", 0, 120)); // NOI18N
        d_pinjam.setForeground(new java.awt.Color(0, 85, 174));
        d_pinjam.setText("0");

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/suitcase_travel.png"))); // NOI18N

        jLabel62.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 85, 174));
        jLabel62.setText("Peminjaman Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(d_pinjam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel61)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel61)
                    .addComponent(d_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 85, 174), 2));

        jLabel63.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 85, 174));
        jLabel63.setText("Alat Kebersihan");

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/housekeeping.png"))); // NOI18N

        label_ak.setFont(new java.awt.Font("Verdana", 0, 120)); // NOI18N
        label_ak.setForeground(new java.awt.Color(0, 85, 174));
        label_ak.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(label_ak)
                .addGap(18, 18, 18)
                .addComponent(jLabel65)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(label_ak, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 85, 174), 2));

        jLabel64.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 85, 174));
        jLabel64.setText("Alat Tulis");

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pencil.png"))); // NOI18N

        label_atk.setFont(new java.awt.Font("Verdana", 0, 120)); // NOI18N
        label_atk.setForeground(new java.awt.Color(0, 85, 174));
        label_atk.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel64)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(label_atk)
                .addGap(28, 28, 28)
                .addComponent(jLabel66)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_atk, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpdashboardcontentLayout = new javax.swing.GroupLayout(jpdashboardcontent);
        jpdashboardcontent.setLayout(jpdashboardcontentLayout);
        jpdashboardcontentLayout.setHorizontalGroup(
            jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdashboardcontentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(21, 21, 21))
            .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                .addGroup(jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jpdashboardcontentLayout.setVerticalGroup(
            jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58)
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addGroup(jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        content_panel.add(jpdashboardcontent, "card2");

        jppeminjamancontent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 85, 174));

        jLabel72.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Data Peminjaman");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel72)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel72)
                .addContainerGap())
        );

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel74MouseClicked(evt);
            }
        });

        btn_tambah_peminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah_peminjaman.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_tambah_peminjaman.setText("Tambah");
        btn_tambah_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah_peminjamanMouseClicked(evt);
            }
        });
        btn_tambah_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_peminjamanActionPerformed(evt);
            }
        });

        btn_edit_peminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit_peminjaman.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_edit_peminjaman.setText("Edit");
        btn_edit_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_peminjamanActionPerformed(evt);
            }
        });

        btn_hapus_peminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus_peminjaman.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_hapus_peminjaman.setText("Hapus");
        btn_hapus_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapus_peminjamanMouseClicked(evt);
            }
        });
        btn_hapus_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_peminjamanActionPerformed(evt);
            }
        });

        tbl_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_peminjaman);

        btnref.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnref.setText("refresh");
        btnref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jppeminjamancontentLayout = new javax.swing.GroupLayout(jppeminjamancontent);
        jppeminjamancontent.setLayout(jppeminjamancontentLayout);
        jppeminjamancontentLayout.setHorizontalGroup(
            jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppeminjamancontentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel74)
                .addGap(21, 21, 21))
            .addGroup(jppeminjamancontentLayout.createSequentialGroup()
                .addComponent(btn_tambah_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnref, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_edit_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_hapus_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jppeminjamancontentLayout.setVerticalGroup(
            jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppeminjamancontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel74)
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_edit_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_tambah_peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        content_panel.add(jppeminjamancontent, "card2");

        jplaporancontent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 85, 174));

        jLabel75.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Generate Laporan");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addContainerGap(821, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel75)
                .addContainerGap())
        );

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 85, 174), 2));

        btnsubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnsubmit.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        btnsubmit.setText("CETAK");
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsubmitMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/suitcase_travel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jplaporancontentLayout = new javax.swing.GroupLayout(jplaporancontent);
        jplaporancontent.setLayout(jplaporancontentLayout);
        jplaporancontentLayout.setHorizontalGroup(
            jplaporancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplaporancontentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel77)
                .addGap(21, 21, 21))
            .addGroup(jplaporancontentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplaporancontentLayout.setVerticalGroup(
            jplaporancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplaporancontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77)
                .addGap(14, 14, 14)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        content_panel.add(jplaporancontent, "card2");

        jpinventariscontent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(0, 85, 174));

        jLabel82.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Data Inventaris");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel82)
                .addContainerGap(850, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel82)
                .addContainerGap())
        );

        jLabel84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel84MouseClicked(evt);
            }
        });

        btn_tambah_inventaris1.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah_inventaris1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_tambah_inventaris1.setText("Tambah");
        btn_tambah_inventaris1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah_inventaris1MouseClicked(evt);
            }
        });

        btn_edit_inventaris.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit_inventaris.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_edit_inventaris.setText("Edit");
        btn_edit_inventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_inventarisActionPerformed(evt);
            }
        });

        btn_hapus_inventaris.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus_inventaris.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_hapus_inventaris.setText("Hapus");
        btn_hapus_inventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_inventarisActionPerformed(evt);
            }
        });

        tbl_inventaris1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_inventaris1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_inventaris1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_inventaris1);

        btn_refresh.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refreshMouseClicked(evt);
            }
        });
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpinventariscontentLayout = new javax.swing.GroupLayout(jpinventariscontent);
        jpinventariscontent.setLayout(jpinventariscontentLayout);
        jpinventariscontentLayout.setHorizontalGroup(
            jpinventariscontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinventariscontentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel84)
                .addGap(21, 21, 21))
            .addGroup(jpinventariscontentLayout.createSequentialGroup()
                .addComponent(btn_tambah_inventaris1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_edit_inventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_hapus_inventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        jpinventariscontentLayout.setVerticalGroup(
            jpinventariscontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinventariscontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel84)
                .addGap(14, 14, 14)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpinventariscontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpinventariscontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_edit_inventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus_inventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_tambah_inventaris1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        content_panel.add(jpinventariscontent, "card2");

        last.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(38, 42, 51));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        cd.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        cd.setForeground(new java.awt.Color(255, 255, 255));
        cd.setText("LAPORAN PER TANGGAL 2019-09-01");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(cd)
                .addGap(21, 21, 21))
        );

        tbl_peminjaman1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_peminjaman1);

        jPanel12.setBackground(new java.awt.Color(38, 42, 51));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Inventaris");

        tbl_inventaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_inventaris);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(38, 42, 51));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Peminjaman");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout lastLayout = new javax.swing.GroupLayout(last);
        last.setLayout(lastLayout);
        lastLayout.setHorizontalGroup(
            lastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lastLayout.setVerticalGroup(
            lastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        content_panel.add(last, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_panel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edit_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_peminjamanActionPerformed
        String id = tbl_peminjaman.getValueAt(baris, 1).toString();
        tambah_peminjam tp = new tambah_peminjam("edit", id);
        tp.setVisible(true);
    }//GEN-LAST:event_btn_edit_peminjamanActionPerformed

    private void jpdashboard9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpdashboard9MouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();
        
        content_panel.add(jpdashboardcontent);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jpdashboard9MouseClicked

    private void jpinventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpinventarisMouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();
        
        content_panel.add(jpinventariscontent);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jpinventarisMouseClicked

    private void jppeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jppeminjamanMouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();
        
        content_panel.add(jppeminjamancontent);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jppeminjamanMouseClicked

    private void jplaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplaporanMouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();
        
        content_panel.add(jplaporancontent);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jplaporanMouseClicked

    private void btn_edit_inventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_inventarisActionPerformed
        String id = tbl_inventaris1.getValueAt(baris, 1).toString();
        tambah_inventaris ti = new tambah_inventaris("edit", id);
        ti.setVisible(true);
        
    }//GEN-LAST:event_btn_edit_inventarisActionPerformed

    private void btn_tambah_inventaris1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah_inventaris1MouseClicked
//       new tambah_inventaris().setVisible(true);
        tambah_inventaris ti = new tambah_inventaris("Tambah", "");
        ti.setVisible(true);
    }//GEN-LAST:event_btn_tambah_inventaris1MouseClicked

    private void btn_tambah_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah_peminjamanMouseClicked
        tambah_peminjam tp = new tambah_peminjam("Tambah", "");
        tp.setVisible(true);
    }//GEN-LAST:event_btn_tambah_peminjamanMouseClicked
    
    int baris;
    private void tbl_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_peminjamanMouseClicked
        baris = tbl_peminjaman.getSelectedRow();
    }//GEN-LAST:event_tbl_peminjamanMouseClicked

    private void btn_hapus_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_peminjamanActionPerformed
       String idWhoWantToBeDelete = tbl_peminjaman.getValueAt(baris, 1).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String Query = "DELETE FROM detail_pinjam WHERE id_peminjaman ='"+idWhoWantToBeDelete+"';";
            int berhasil = stmt.executeUpdate(Query);
            String Querydua = "DELETE FROM peminjaman WHERE id_peminjaman ='"+idWhoWantToBeDelete+"';";
            int berhasildua = stmt.executeUpdate(Querydua);
            if(berhasildua == 1){
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                dtm.getDataVector().removeAllElements();
                showDataPeminjaman();
            }else{
                JOptionPane.showMessageDialog(null,"Data gagal Dihapus");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_hapus_peminjamanActionPerformed

    private void btn_hapus_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapus_peminjamanMouseClicked
         
    }//GEN-LAST:event_btn_hapus_peminjamanMouseClicked

    private void tbl_inventaris1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_inventaris1MouseClicked
        baris = tbl_inventaris1.getSelectedRow();
    }//GEN-LAST:event_tbl_inventaris1MouseClicked

    private void btn_hapus_inventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_inventarisActionPerformed
       String idWhoWantToBeDelete = tbl_inventaris1.getValueAt(baris, 1).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String Query = "DELETE FROM inventaris WHERE nama_barang ='"+idWhoWantToBeDelete+"';";
            int berhasil = stmt.executeUpdate(Query);
            if(berhasil == 1){
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                dtm.getDataVector().removeAllElements();
                showDataInventaris();
            }else{
                JOptionPane.showMessageDialog(null,"Data gagal Dihapus");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_hapus_inventarisActionPerformed

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        this.dispose();
        new loginpetugas().setVisible(true);
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseClicked
        this.dispose();
        new loginpetugas().setVisible(true);
    }//GEN-LAST:event_jLabel74MouseClicked

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
       this.dispose();
        new loginpetugas().setVisible(true);
    }//GEN-LAST:event_jLabel77MouseClicked

    private void jLabel84MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel84MouseClicked
        this.dispose();
        new loginpetugas().setVisible(true);
    }//GEN-LAST:event_jLabel84MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        setExtendedState(frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btn_tambah_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_peminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambah_peminjamanActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseClicked
        showDataInventaris();
    }//GEN-LAST:event_btn_refreshMouseClicked

    private void btnrefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefMouseClicked
        showDataPeminjaman();
    }//GEN-LAST:event_btnrefMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       showDashboard();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseClicked
       content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();
        
        content_panel.add(last);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_btnsubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit_inventaris;
    private javax.swing.JButton btn_edit_peminjaman;
    private javax.swing.JButton btn_hapus_inventaris;
    private javax.swing.JButton btn_hapus_peminjaman;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_tambah_inventaris1;
    private javax.swing.JButton btn_tambah_peminjaman;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel cd;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel d_pinjam;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpdashboard9;
    private javax.swing.JPanel jpdashboardcontent;
    private javax.swing.JPanel jpinventaris;
    private javax.swing.JPanel jpinventariscontent;
    private javax.swing.JPanel jplaporan;
    private javax.swing.JPanel jplaporancontent;
    private javax.swing.JPanel jppeminjaman;
    private javax.swing.JPanel jppeminjamancontent;
    private javax.swing.JLabel label_ak;
    private javax.swing.JLabel label_atk;
    private javax.swing.JPanel last;
    private javax.swing.JPanel side_panel9;
    private javax.swing.JTable tbl_inventaris;
    private javax.swing.JTable tbl_inventaris1;
    private javax.swing.JTable tbl_peminjaman;
    private javax.swing.JTable tbl_peminjaman1;
    // End of variables declaration//GEN-END:variables
   
    DefaultTableModel dtm;
    
    private void showDataPeminjaman()   {
       String[] kolom = {"NO","Id","Barang Dipinjam","Jumlah","Tanggal Pinjam","Status","NIP Peminjam"};
       
       dtm = new DefaultTableModel(null, kolom);
       
       try{
         Statement stmt = koneksi.createStatement();
         String query = "SELECT peminjaman.id_peminjaman, inventaris.nama_barang, detail_pinjam.jumlah,peminjaman.tanggal_pinjam,peminjaman.nip, "
                 + "peminjaman.status_peminjaman FROM detail_pinjam JOIN inventaris ON detail_pinjam.id_inventaris = "
                 + "inventaris.id_inventaris JOIN peminjaman ON peminjaman.id_peminjaman = detail_pinjam.id_peminjaman";
         
         ResultSet rs = stmt.executeQuery(query);
         int no = 1;
         while(rs.next()){
             String id_peminjaman = rs.getString("id_peminjaman");
             String nama_barang = rs.getString("nama_barang");
             String jumlah = rs.getString("jumlah");
             String tanggal_pinjam = rs.getString("tanggal_pinjam");
             String nip = rs.getString("nip");
             String status_peminjaman = rs.getString("status_peminjaman");
             dtm.addRow(new String[]{no+"",id_peminjaman,nama_barang,jumlah,tanggal_pinjam,nip,status_peminjaman});
             no++;
         }
       }catch (SQLException ex){
           ex.printStackTrace();
       }
       tbl_peminjaman.setModel(dtm);
    }

    private void showDataInventaris() {
        String[] kolom = {"NO","Nama Barang","Kondisi","Keterangan","Jumlah","Jenis","Ruangan","Petugas"};
       
       dtm = new DefaultTableModel(null, kolom);
       
       try{
         Statement stmt = koneksi.createStatement();
         String query = "SELECT inventaris.nama_barang, inventaris.kondisi, inventaris.keterangan, inventaris.jumlah, "
                 + "jenis.nama_jenis, ruang.nama_ruang, petugas.nama_petugas FROM inventaris JOIN jenis ON inventaris.id_jenis "
                 + "= jenis.id_jenis JOIN ruang ON inventaris.id_ruang = ruang.id_ruang JOIN petugas ON inventaris.id_petugas = "
                 + "petugas.id_petugas";
         
         ResultSet rs = stmt.executeQuery(query);
         int no = 1;
         while(rs.next()){
             String nama_barang = rs.getString("nama_barang");
             String kondisi = rs.getString("kondisi");
             String keterangan = rs.getString("keterangan");
             String jumlah = rs.getString("jumlah");
             String nama_jenis = rs.getString("nama_jenis");
             String nama_ruang = rs.getString("nama_ruang");
             String nama_petugas = rs.getString("nama_petugas");
             dtm.addRow(new String[]{no+"",nama_barang,kondisi,keterangan,jumlah,nama_jenis,nama_ruang,nama_petugas});
             no++;
         }
       }catch (SQLException ex){
           ex.printStackTrace();
       }
       tbl_inventaris1.setModel(dtm);
    }

    private void showDashboard() {
         try{
        Statement stmt = koneksi.createStatement();
        String query = "SELECT COUNT(id_peminjaman) AS 'jumlah' FROM peminjaman";
        ResultSet rs = stmt.executeQuery(query);
        rs.next();
        d_pinjam.setText(rs.getString("jumlah"));
         } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
         try{
        Statement stmt = koneksi.createStatement();
        String query = "SELECT COUNT(id_inventaris) AS 'jumlah' FROM inventaris WHERE id_jenis = 1";
        ResultSet rs = stmt.executeQuery(query);
        rs.next();
        label_ak.setText(rs.getString("jumlah"));
         } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
         try{
        Statement stmt = koneksi.createStatement();
        String query = "SELECT COUNT(id_inventaris) AS 'jumlah' FROM inventaris WHERE id_jenis = 2";
        ResultSet rs = stmt.executeQuery(query);
        rs.next();
        label_atk.setText(rs.getString("jumlah"));
         } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LaporanAdmin() {
       String[] kolom = {"NO","Nama Barang","Kondisi","Keterangan","Jumlah","Jenis","Ruangan","Petugas"};
       
       dtm = new DefaultTableModel(null, kolom);
       
       try{
         Statement stmt = koneksi.createStatement();
         String query = "SELECT inventaris.nama_barang, inventaris.kondisi, inventaris.keterangan, inventaris.jumlah, "
                 + "jenis.nama_jenis, ruang.nama_ruang, petugas.nama_petugas FROM inventaris JOIN jenis ON inventaris.id_jenis "
                 + "= jenis.id_jenis JOIN ruang ON inventaris.id_ruang = ruang.id_ruang JOIN petugas ON inventaris.id_petugas = "
                 + "petugas.id_petugas";
         
         ResultSet rs = stmt.executeQuery(query);
         int no = 1;
         while(rs.next()){
             String nama_barang = rs.getString("nama_barang");
             String kondisi = rs.getString("kondisi");
             String keterangan = rs.getString("keterangan");
             String jumlah = rs.getString("jumlah");
             String nama_jenis = rs.getString("nama_jenis");
             String nama_ruang = rs.getString("nama_ruang");
             String nama_petugas = rs.getString("nama_petugas");
             dtm.addRow(new String[]{no+"",nama_barang,kondisi,keterangan,jumlah,nama_jenis,nama_ruang,nama_petugas});
             no++;
         }
       }catch (SQLException ex){
           ex.printStackTrace();
       }
       tbl_inventaris.setModel(dtm);
    }
   private void laporanAdmin1(){
       String[] kolom = {"NO","Id","Barang Dipinjam","Jumlah","Tanggal Pinjam","Status","NIP Peminjam"};
       
       dtm = new DefaultTableModel(null,kolom);
       try{
           Statement stmt = koneksi.createStatement();
           String query = "SELECT peminjaman.id_peminjaman,inventaris.nama_barang,detail_pinjam.jumlah,peminjaman.tanggal_pinjam,peminjaman.nip,"
                   + "peminjaman.status_peminjaman FROM detail_pinjam JOIN inventaris ON detail_pinjam.id_inventaris ="
                   + "inventaris.id_inventaris JOIN peminjaman ON peminjaman.id_peminjaman = detail_pinjam.id_peminjamam";
           
           ResultSet rs = stmt.executeQuery(query);
           int no = 1;
           while(rs.next()){
               String id_peminjaman = rs.getString("id_peminjaman");
               String nama_barang = rs.getString("nama_barang");
               String jumlah = rs.getString("jumlah");
               String tanggal_pinjam = rs.getString("tanggal_pinjam");
               String nip = rs.getString("nip");
               String status_peminjaman = rs.getString("status_peminjaman");
               dtm.addRow(new String[]{no+"",id_peminjaman,nama_barang,jumlah,tanggal_pinjam,nip,status_peminjaman});
               no++;
           }
       } catch (SQLException ex){
           ex.printStackTrace();
       }
       tbl_peminjaman1.setModel(dtm);
   }
}