/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasisarpras;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SMK 4
 */
public class Operator extends javax.swing.JFrame {

    /**
     * Creates new form Operator
     */
    Connection koneksi;
    public Operator() {
        initComponents();
        koneksi = KoneksiDatabase.getKoneksi();
        showDashboard();
        showDataPeminjaman();
        showDataInventaris();
        //agar ditengah page nya
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2 ;
        int y = layar.height / 2 - this.getSize().height / 2 ;
        
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        side_panel = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jpdashboard9 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jpinventaris = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jppeminjaman = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        jpdashboardcontent = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        c_pinjam = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jppeminjamancontent = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        btn_tambah_peminjaman = new javax.swing.JButton();
        btn_edit_peminjaman = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_peminjaman = new javax.swing.JTable();
        jpinventariscontent1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_inventaris1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sarana dan Prasarana SMK4 | Operator");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        side_panel.setBackground(new java.awt.Color(38, 42, 51));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/smk4(1).png"))); // NOI18N

        jLabel54.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Versi 1.0");

        jLabel55.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Operator");

        jpdashboard9.setBackground(new java.awt.Color(38, 42, 51));
        jpdashboard9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpdashboard9MouseClicked(evt);
            }
        });

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Home_20px.png"))); // NOI18N

        jLabel57.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Dashboard");

        javax.swing.GroupLayout jpdashboard9Layout = new javax.swing.GroupLayout(jpdashboard9);
        jpdashboard9.setLayout(jpdashboard9Layout);
        jpdashboard9Layout.setHorizontalGroup(
            jpdashboard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdashboard9Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel57)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpdashboard9Layout.setVerticalGroup(
            jpdashboard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdashboard9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpdashboard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addContainerGap())
        );

        jpinventaris.setBackground(new java.awt.Color(38, 42, 51));
        jpinventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpinventarisMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Broom_20px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inventaris");

        javax.swing.GroupLayout jpinventarisLayout = new javax.swing.GroupLayout(jpinventaris);
        jpinventaris.setLayout(jpinventarisLayout);
        jpinventarisLayout.setHorizontalGroup(
            jpinventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinventarisLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpinventarisLayout.setVerticalGroup(
            jpinventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinventarisLayout.createSequentialGroup()
                .addGroup(jpinventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jppeminjaman.setBackground(new java.awt.Color(38, 42, 51));
        jppeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jppeminjamanMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Suitcase_20px_1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Peminjaman");

        javax.swing.GroupLayout jppeminjamanLayout = new javax.swing.GroupLayout(jppeminjaman);
        jppeminjaman.setLayout(jppeminjamanLayout);
        jppeminjamanLayout.setHorizontalGroup(
            jppeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppeminjamanLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jppeminjamanLayout.setVerticalGroup(
            jppeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppeminjamanLayout.createSequentialGroup()
                .addGroup(jppeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout side_panelLayout = new javax.swing.GroupLayout(side_panel);
        side_panel.setLayout(side_panelLayout);
        side_panelLayout.setHorizontalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpdashboard9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpinventaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jppeminjaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_panelLayout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_panelLayout.createSequentialGroup()
                        .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel54))
                        .addGap(86, 86, 86))))
        );
        side_panelLayout.setVerticalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addGap(36, 36, 36)
                .addComponent(jpdashboard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpinventaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jppeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content_panel.setBackground(new java.awt.Color(255, 255, 255));
        content_panel.setLayout(new java.awt.CardLayout());

        jpdashboardcontent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 85, 174));

        jLabel59.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addContainerGap(841, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addContainerGap())
        );

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 85, 174), 2));

        c_pinjam.setFont(new java.awt.Font("Verdana", 0, 120)); // NOI18N
        c_pinjam.setForeground(new java.awt.Color(0, 85, 174));
        c_pinjam.setText("0");

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/suitcase_travel.png"))); // NOI18N

        jLabel62.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 85, 174));
        jLabel62.setText("Peminjaman Barang");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(c_pinjam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel61)))
                .addGap(273, 273, 273))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpdashboardcontentLayout = new javax.swing.GroupLayout(jpdashboardcontent);
        jpdashboardcontent.setLayout(jpdashboardcontentLayout);
        jpdashboardcontentLayout.setHorizontalGroup(
            jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdashboardcontentLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdashboardcontentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(21, 21, 21))
            .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpdashboardcontentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406))
        );
        jpdashboardcontentLayout.setVerticalGroup(
            jpdashboardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdashboardcontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );

        content_panel.add(jpdashboardcontent, "card2");

        jppeminjamancontent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 85, 174));

        jLabel72.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Data Peminjaman");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel72)
                .addContainerGap(771, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel72)
                .addContainerGap())
        );

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel74MouseClicked(evt);
            }
        });

        btn_tambah_peminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah_peminjaman.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_tambah_peminjaman.setText("Tambah");
        btn_tambah_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah_peminjamanMouseClicked(evt);
            }
        });

        btn_edit_peminjaman.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit_peminjaman.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_edit_peminjaman.setText("Edit");
        btn_edit_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_peminjamanActionPerformed(evt);
            }
        });

        tbl_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_peminjaman);

        javax.swing.GroupLayout jppeminjamancontentLayout = new javax.swing.GroupLayout(jppeminjamancontent);
        jppeminjamancontent.setLayout(jppeminjamancontentLayout);
        jppeminjamancontentLayout.setHorizontalGroup(
            jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppeminjamancontentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel74)
                .addGap(21, 21, 21))
            .addGroup(jppeminjamancontentLayout.createSequentialGroup()
                .addComponent(btn_tambah_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_edit_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jppeminjamancontentLayout.setVerticalGroup(
            jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppeminjamancontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel74)
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jppeminjamancontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        content_panel.add(jppeminjamancontent, "card2");

        jpinventariscontent1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(0, 85, 174));

        jLabel83.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Data Inventaris");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel83)
                .addContainerGap())
        );

        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jLabel85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel85MouseClicked(evt);
            }
        });

        tbl_inventaris1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_inventaris1);

        javax.swing.GroupLayout jpinventariscontent1Layout = new javax.swing.GroupLayout(jpinventariscontent1);
        jpinventariscontent1.setLayout(jpinventariscontent1Layout);
        jpinventariscontent1Layout.setHorizontalGroup(
            jpinventariscontent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinventariscontent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel85)
                .addGap(21, 21, 21))
            .addComponent(jScrollPane3)
        );
        jpinventariscontent1Layout.setVerticalGroup(
            jpinventariscontent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinventariscontent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel85)
                .addGap(14, 14, 14)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        content_panel.add(jpinventariscontent1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpdashboard9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpdashboard9MouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();

        content_panel.add(jpdashboardcontent);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jpdashboard9MouseClicked

    private void jpinventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpinventarisMouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();

        content_panel.add(jpinventariscontent1);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jpinventarisMouseClicked

    private void jppeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jppeminjamanMouseClicked
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();

        content_panel.add(jppeminjamancontent);
        content_panel.repaint();
        content_panel.revalidate();
    }//GEN-LAST:event_jppeminjamanMouseClicked

    private void btn_edit_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_peminjamanActionPerformed
        String id = tbl_peminjaman.getValueAt(baris, 1).toString();
        tambah_peminjam tp = new tambah_peminjam("edit", id);
        tp.setVisible(true);
    }//GEN-LAST:event_btn_edit_peminjamanActionPerformed

    private void btn_tambah_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah_peminjamanMouseClicked
        tambah_peminjam tp = new tambah_peminjam("Tambah", "");
        tp.setVisible(true);
    }//GEN-LAST:event_btn_tambah_peminjamanMouseClicked

    int baris;
    private void tbl_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_peminjamanMouseClicked
        baris = tbl_peminjaman.getSelectedRow();
    }//GEN-LAST:event_tbl_peminjamanMouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        this.dispose();
        new loginpegawai().setVisible(true);
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseClicked
        this.dispose();
        new loginpegawai().setVisible(true);
    }//GEN-LAST:event_jLabel74MouseClicked

    private void jLabel85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel85MouseClicked
        this.dispose();
        new loginpegawai().setVisible(true);
    }//GEN-LAST:event_jLabel85MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        showDashboard();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit_peminjaman;
    private javax.swing.JButton btn_tambah_peminjaman;
    private javax.swing.JLabel c_pinjam;
    private javax.swing.JPanel content_panel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpdashboard9;
    private javax.swing.JPanel jpdashboardcontent;
    private javax.swing.JPanel jpinventaris;
    private javax.swing.JPanel jpinventariscontent1;
    private javax.swing.JPanel jppeminjaman;
    private javax.swing.JPanel jppeminjamancontent;
    private javax.swing.JPanel side_panel;
    private javax.swing.JTable tbl_inventaris1;
    private javax.swing.JTable tbl_peminjaman;
    // End of variables declaration//GEN-END:variables
 
    DefaultTableModel dtm;
    
    private void showDataPeminjaman()   {
       String[] kolom = {"NO", "Barang Dipinjam","Jumlah","Tanggal Pinjam","Status","NIP Peminjam"};
       
       dtm = new DefaultTableModel(null, kolom);
       
       try{
         Statement stmt = koneksi.createStatement();
         String query = "SELECT inventaris.nama_barang, detail_pinjam.jumlah,peminjaman.tanggal_pinjam,peminjaman.nip, "
                 + "peminjaman.status_peminjaman FROM detail_pinjam JOIN inventaris ON detail_pinjam.id_inventaris = "
                 + "inventaris.id_inventaris JOIN peminjaman ON peminjaman.id_peminjaman = detail_pinjam.id_peminjaman";
         
         ResultSet rs = stmt.executeQuery(query);
         int no = 1;
         while(rs.next()){
             String nama_barang = rs.getString("nama_barang");
             String jumlah = rs.getString("jumlah");
             String tanggal_pinjam = rs.getString("tanggal_pinjam");
             String nip = rs.getString("nip");
             String status_peminjaman = rs.getString("status_peminjaman");
             dtm.addRow(new String[]{no+"",nama_barang,jumlah,tanggal_pinjam,nip,status_peminjaman});
             no++;
         }
       }catch (SQLException ex){
           ex.printStackTrace();
       }
       tbl_peminjaman.setModel(dtm);
    }

    private void showDataInventaris() {
        String[] kolom = {"NO", "Nama Barang","Kondisi","Keterangan","Jumlah","Jenis","Ruangan","Petugas"};
       
       dtm = new DefaultTableModel(null, kolom);
       
       try{
         Statement stmt = koneksi.createStatement();
         String query = "SELECT inventaris.nama_barang, inventaris.kondisi, inventaris.keterangan, inventaris.jumlah, "
                 + "jenis.nama_jenis, ruang.nama_ruang, petugas.nama_petugas FROM inventaris JOIN jenis ON inventaris.id_jenis "
                 + "= jenis.id_jenis JOIN ruang ON inventaris.id_ruang = ruang.id_ruang JOIN petugas ON inventaris.id_petugas = "
                 + "petugas.id_petugas";
         
         ResultSet rs = stmt.executeQuery(query);
         int no = 1;
         while(rs.next()){
             String nama_barang = rs.getString("nama_barang");
             String kondisi = rs.getString("kondisi");
             String keterangan = rs.getString("keterangan");
             String jumlah = rs.getString("jumlah");
             String nama_jenis = rs.getString("nama_jenis");
             String nama_ruang = rs.getString("nama_ruang");
             String nama_petugas = rs.getString("nama_petugas");
             dtm.addRow(new String[]{no+"",nama_barang,kondisi,keterangan,jumlah,nama_jenis,nama_ruang,nama_petugas});
             no++;
         }
       }catch (SQLException ex){
           ex.printStackTrace();
       }
       tbl_inventaris1.setModel(dtm);
    }
    
    private void showDashboard() {
         try{
        Statement stmt = koneksi.createStatement();
        String query = "SELECT COUNT(id_peminjaman) AS 'jumlah' FROM peminjaman";
        ResultSet rs = stmt.executeQuery(query);
        rs.next();
        c_pinjam.setText(rs.getString("jumlah"));
         } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
